# More information on the parameters can be found here: https://documentation.red-gate.com/flyway/reference/configuration

[environments.dev]
url = "jdbc:postgresql://localhost:5432/${CB_DATABASE}"
user = "${CB_USER_DB}"
password = "${CB_PASSWORD_DB}"
schemas = ["public"]
connectRetries = 5
connectRetriesInterval = 60
#driver = 
# initSql =
# jdbcProperties =
# resolvers =

# [environments.build]
# url = "jdbc:sqlite::memory:"
# user = "buildUser"
# password = "buildPassword"

#[flyway]
# environment = "sample" # It is recommended to configure environment as a commandline argument. This allows using different environments depending on the caller.
# locations = ["filesystem:path/to/sql/files"]
# jarDirs = ["path/to/java/migrations"]

# [flyway.check]
# buildEnvironment = "build"